FROM betagouv/transport:0.4.3

RUN apk add inotify-tools
RUN apk add postgresql-client>=11

RUN mkdir /app/
RUN mkdir /app/_build
RUN mkdir /app/deps/
WORKDIR /app/

# fetch a wait-for-it script to wait for postgres startup
ADD https://raw.githubusercontent.com/vishnubob/wait-for-it/54d1f0bfeb6557adf8a3204455389d0901652242/wait-for-it.sh /opt/bin/
RUN chmod +x /opt/bin/wait-for-it.sh

ADD docker_phoenix_startup.sh /docker_phoenix_startup.sh
RUN chmod +x /docker_phoenix_startup.sh

ADD mix.exs mix.lock /app/
ADD config /app/config/
ADD apps /app/apps/

CMD [ "/docker_phoenix_startup.sh" ]
