FROM betagouv/transport:elixir-1.12.2-erlang-24.0.4-ubuntu-focal-20210325-with-transport-tools

RUN apt-get install -y git inotify-tools postgresql-client>=11

RUN mkdir /app/
RUN mkdir /app/_build
RUN mkdir /app/deps/
WORKDIR /app/
RUN mv /transport-tools /app

# fetch a wait-for-it script to wait for postgres startup
ADD https://raw.githubusercontent.com/vishnubob/wait-for-it/81b1373f17855a4dc21156cfe1694c31d7d1792e/wait-for-it.sh /opt/bin/
RUN chmod +x /opt/bin/wait-for-it.sh

ADD docker_phoenix_startup.sh /docker_phoenix_startup.sh
RUN chmod +x /docker_phoenix_startup.sh

ADD mix.exs mix.lock /app/
ADD config /app/config/
ADD apps /app/apps/


CMD [ "/docker_phoenix_startup.sh" ]
