Mox.defmock(Transport.ExAWS.Mock, for: ExAws.Behaviour)
Mox.defmock(Transport.HTTPoison.Mock, for: HTTPoison.Base)
Mox.defmock(Validation.Validator.Mock, for: Shared.Validation.Validator)
Mox.defmock(Shared.Validation.GBFSValidator.Mock, for: Shared.Validation.GBFSValidator.Wrapper)
Mox.defmock(Transport.Rambo.Mock, for: Transport.RamboLauncher)
Mox.defmock(Transport.Notifications.FetcherMock, for: Transport.Notifications.Fetcher)
