defmodule TransportWeb.CoreComponents do
  @moduledoc """
  Provides core UI components, modeled on the ones generated by `mix phx.new` (Phoenix 1.8).

  The generated components rely on Tailwind CSS and daisyUI: these ones render the markup
  of [template.data.gouv.fr](https://github.com/etalab/template.data.gouv.fr) instead, the same
  markup as the former `PhoenixHTMLHelpers` based helpers, so that the existing styles apply.

  Some components, such as `<.link>` and `<.form>`, are defined in `Phoenix.Component`.
  """
  use Phoenix.Component

  @doc """
  Renders a button, or a link styled as a button when given `href`, `navigate` or `patch`.

  ## Examples

      <.button>Send!</.button>
      <.button class="button-outline primary">Send!</.button>
      <.button href={~p"/"}>Home</.button>
  """
  attr(:rest, :global, include: ~w(href navigate patch method download name value disabled form))
  attr(:class, :any, default: "button")
  attr(:type, :string, default: "submit")
  slot(:inner_block, required: true)

  def button(%{rest: rest} = assigns) do
    if rest[:href] || rest[:navigate] || rest[:patch] do
      ~H"""
      <.link class={@class} {@rest}>{render_slot(@inner_block)}</.link>
      """
    else
      ~H"""
      <button class={@class} type={@type} {@rest}>{render_slot(@inner_block)}</button>
      """
    end
  end

  @doc """
  Renders an input with an optional label and its error messages.

  A `Phoenix.HTML.FormField` may be passed as argument, which is used to retrieve
  the input name, id, and values. Otherwise all attributes may be passed explicitly.

  ## Types

  This function accepts all HTML input types, considering that:

    * You may also set `type="select"` to render a `<select>` tag

    * `type="textarea"` renders a `<textarea>`, which grows with its content when `autoexpand` is set

    * `type="search"` adds the magnifier icon

    * `type="checkbox"` is used exclusively to render boolean values

  Unsupported types, such as radio, are best written directly in your templates.

  ## Examples

  ```heex
  <.input field={@form[:email]} type="email" label="Email" />
  <.input name="my-input" errors={["oh no!"]} />
  ```

  ## Select type

  When using `type="select"`, you must pass the `options` and optionally
  a `value` to mark which option should be preselected.

  ```heex
  <.input field={@form[:user_type]} type="select" options={["Admin": "admin", "User": "user"]} />
  ```

  For more information on what kind of data can be passed to `options` see
  [`options_for_select`](https://phoenix-html.hexdocs.pm/Phoenix.HTML.Form.html#options_for_select/2).
  """
  attr(:id, :any, default: nil)
  attr(:name, :any)
  attr(:label, :string, default: nil)
  attr(:value, :any)

  attr(:type, :string,
    default: "text",
    values: ~w(checkbox color date datetime-local email file month number password
               search select tel text textarea time url week hidden)
  )

  attr(:field, Phoenix.HTML.FormField, doc: "a form field struct retrieved from the form, for example: @form[:email]")

  attr(:errors, :list, default: [])
  attr(:checked, :boolean, doc: "the checked flag for checkbox inputs")
  attr(:prompt, :string, default: nil, doc: "the prompt for select inputs")
  attr(:options, :list, doc: "the options to pass to Phoenix.HTML.Form.options_for_select/2")
  attr(:multiple, :boolean, default: false, doc: "the multiple flag for select inputs")
  attr(:autoexpand, :boolean, default: false, doc: "makes a textarea grow with its content")
  attr(:wrapper, :boolean, default: true, doc: "wraps the label, the input and its errors in a form__group div")

  attr(:rest, :global, include: ~w(accept autocomplete capture cols disabled form list max maxlength min minlength
                multiple pattern placeholder readonly required rows size step))

  def input(%{field: %Phoenix.HTML.FormField{} = field} = assigns) do
    errors = if Phoenix.Component.used_input?(field), do: field.errors, else: []

    assigns
    |> assign(field: nil, id: assigns.id || field.id)
    |> assign(:errors, Enum.map(errors, &translate_error(&1)))
    |> assign_new(:name, fn -> if assigns.multiple, do: field.name <> "[]", else: field.name end)
    |> assign_new(:value, fn -> field.value end)
    |> input()
  end

  def input(%{type: "hidden"} = assigns) do
    ~H"""
    <input type="hidden" id={@id} name={@name} value={@value} {@rest} />
    """
  end

  def input(%{type: "checkbox"} = assigns) do
    assigns =
      assign_new(assigns, :checked, fn ->
        Phoenix.HTML.Form.normalize_value("checkbox", assigns[:value])
      end)

    ~H"""
    <input type="hidden" name={@name} value="false" disabled={@rest[:disabled]} form={@rest[:form]} />
    <input type="checkbox" id={@id} name={@name} value="true" checked={@checked} {@rest} />
    <.error :for={msg <- @errors}>{msg}</.error>
    """
  end

  def input(%{type: "select"} = assigns) do
    ~H"""
    <.form_group wrapper={@wrapper}>
      <label :if={@label} for={@id}>{@label}</label>
      <select id={@id} name={@name} multiple={@multiple} {@rest}>
        <option :if={@prompt} value="">{@prompt}</option>
        {Phoenix.HTML.Form.options_for_select(@options, @value)}
      </select>
      <.error :for={msg <- @errors}>{msg}</.error>
    </.form_group>
    """
  end

  def input(%{type: "textarea", autoexpand: true} = assigns) do
    ~H"""
    <.form_group wrapper={@wrapper}>
      <label :if={@label} for={@id}>{@label}</label>
      <div class="autoexpand">
        <textarea id={@id} name={@name} phx-hook="TextareaAutoexpand" {@rest}>{Phoenix.HTML.Form.normalize_value("textarea", @value)}</textarea>
      </div>
      <.error :for={msg <- @errors}>{msg}</.error>
    </.form_group>
    """
  end

  def input(%{type: "textarea"} = assigns) do
    ~H"""
    <.form_group wrapper={@wrapper}>
      <label :if={@label} for={@id}>{@label}</label>
      <textarea id={@id} name={@name} {@rest}>{Phoenix.HTML.Form.normalize_value("textarea", @value)}</textarea>
      <.error :for={msg <- @errors}>{msg}</.error>
    </.form_group>
    """
  end

  def input(%{type: "search"} = assigns) do
    ~H"""
    <.form_group wrapper={@wrapper}>
      <label :if={@label} for={@id}>{@label}</label>
      <div class="">
        <i class="fas icon--magnifier" id="magnifier"></i>
        <input type="search" id={@id} name={@name} value={Phoenix.HTML.Form.normalize_value("search", @value)} {@rest} />
      </div>
      <.error :for={msg <- @errors}>{msg}</.error>
    </.form_group>
    """
  end

  # All other inputs text, email, number, file, url, etc. are handled here...
  def input(assigns) do
    ~H"""
    <.form_group wrapper={@wrapper}>
      <label :if={@label} for={@id}>{@label}</label>
      <input
        type={@type}
        id={@id}
        name={@name}
        value={if @type != "file", do: Phoenix.HTML.Form.normalize_value(@type, @value)}
        {@rest}
      />
      <.error :for={msg <- @errors}>{msg}</.error>
    </.form_group>
    """
  end

  attr(:wrapper, :boolean, required: true)
  slot(:inner_block, required: true)

  defp form_group(%{wrapper: true} = assigns) do
    ~H"""
    <div class="form__group">{render_slot(@inner_block)}</div>
    """
  end

  defp form_group(assigns) do
    ~H"""
    {render_slot(@inner_block)}
    """
  end

  # Helper used by inputs to generate form errors
  slot(:inner_block, required: true)

  defp error(assigns) do
    ~H"""
    <span class="help-block">{render_slot(@inner_block)}</span>
    """
  end

  @doc """
  Translates an error message using gettext.
  """
  def translate_error({msg, opts}) do
    # When using gettext, we typically pass the strings we want
    # to translate as a static argument:
    #
    #     # Translate the number of files with plural rules
    #     dngettext("errors", "1 file", "%{count} files", count)
    #
    # However the error messages in our forms and APIs are generated
    # dynamically, so we need to translate them by calling Gettext
    # with our gettext backend as first argument. Translations are
    # available in the errors.po file (as we use the "errors" domain).
    if count = opts[:count] do
      Gettext.dngettext(TransportWeb.Gettext, "errors", msg, msg, count, opts)
    else
      Gettext.dgettext(TransportWeb.Gettext, "errors", msg, opts)
    end
  end

  @doc """
  Translates the errors for a field from a keyword list of errors.
  """
  def translate_errors(errors, field) when is_list(errors) do
    for {^field, {msg, opts}} <- errors, do: translate_error({msg, opts})
  end
end
