baseURL = "https://blog.transport.data.gouv.fr/"
languageCode = "fr"
title = "Et PAN !"
theme = "mediumish"
summaryLength = 25
enableEmoji = true
publishDir = "public"
#disqusShortname = "your-shortname-here"

[params]
  marianne = "/images/logo-marianne.svg"
  logo = "/images/logo-header.svg"
  description = "Le blog de transport.data.gouv.fr"
  title = "Et PAN !"
  #mailchimp = "you can provide a mailchimp-link here"

[params.author]
  #name = ""
  #thumbnail = ""
  #description = ""

[params.reutilisateurs]
  msg = "Nous réalisons une série d’entretiens avec différents réutilisateurs des données mises à disposition sur le Point d’Accès National, afin de valoriser l’usage qui est fait de la donnée de transport et illustrer des différents cas d’usage qu’elle peut avoir."
  alertbar = false

[params.social]
  github = "<username>"
  linkedin = "<username>"
  xing = "<username>"
  medium = "<username>"
  twitter = "<username>"
