name: Sentry release integration
on:
  push:
    branches:
      - master
jobs:
  # See https://github.com/marketplace/actions/sentry-release
  # See https://sentry.io/settings/transport-data-gouv-fr/developer-settings/github-action-release-integration-f9f6ff/
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 5
      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: 'transport-data-gouv-fr'
          SENTRY_PROJECT: 'transport-site'
        with:
          environment: prod
